# Generated by Django 4.0.3 on 2022-03-26 01:45

from django.db import migrations, models
import course.models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=300, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=course.models.post_storage_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='course.course')),
            ],
        ),
    ]
