# Generated by Django 4.0.3 on 2022-03-24 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='questions',
        ),
        migrations.AddField(
            model_name='course',
            name='codeInvitation',
            field=models.CharField(blank=True, default=b'N', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Course_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
