# Generated by Django 4.0.3 on 2022-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_assignment_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description_short',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
