# Generated by Django 4.0.3 on 2022-03-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='questions',
        ),
    ]
