# Generated by Django 4.0.3 on 2022-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_homework_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='comentary',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
