# Generated by Django 4.0.3 on 2022-04-17 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_homework_comentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='now_calification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
